Added additional cmd checks
git-svn-id: https://oss.gonicus.de/repositories/gosa/trunk@11245 594d385d-05f5-0310-b6e9-bd551577e9d8

diff --git a/contrib/make-gosa-package b/contrib/make-gosa-package
--- a/contrib/make-gosa-package
+++ b/contrib/make-gosa-package
@@ -44,10 +44,12 @@ usage() {
 	exit 1
 }
 
-if ! which dh-make-gosa >/dev/null; then
-	echo "Error: cannot find dh-make-gosa binary in path!";
-	exit 1
-fi
+for cmd in dh-make-gosa debchange dpkg-buildpackage dpkg-source svn; do
+  if ! which $cmd >/dev/null; then
+  	echo "Error: cannot find '$cmd' command in path!";
+  	exit 1
+  fi
+done
 
 # Import command line parameters
 PARMS=`getopt -o brscip:,h --long branch,changelog,plugins,section,si-section,release:,help -n "${0##*/}" -- "$@"`
