More cleanup for apache 2.4/2.2 side by side
git-svn-id: https://oss.gonicus.de/repositories/gosa/trunk@21154 594d385d-05f5-0310-b6e9-bd551577e9d8

diff --git a/debian/gosa.postinst b/debian/gosa.postinst
--- a/debian/gosa.postinst
+++ b/debian/gosa.postinst
@@ -28,6 +28,7 @@ esac
 # Set ID's
 WEBUSER="www-data"
 WEBGROUP="www-data"
+CONF="gosa"
 
 # Create empty inclusion file for apache
 if [ ! -f /etc/gosa/gosa.secrets ]; then
@@ -35,40 +36,18 @@ if [ ! -f /etc/gosa/gosa.secrets ]; then
     chmod 600 /etc/gosa/gosa.secrets
 fi
 
-if [ -d /etc/apache2/conf-available ]; then
-
-  # Copy GOsa configuration to conf-available directories
-  #if [ ! -L /etc/apache2/conf-available/gosa.conf ]; then
-
-  #  # Remove old instances of this file
-  #  if [ -f /etc/apache2/conf-available/gosa.conf ]; then
-  #    echo "Found old gosa apache configuration in /etc/apache2/conf-available - moving it to gosa.conf.orig..."
-  #    echo "Please check for changes in /etc/apache2/conf-available/gosa.conf if you modified this file!"
-  #    mv /etc/apache2/conf-available/gosa.conf /etc/apache2/conf-available/gosa.conf.orig
-  #  fi
-
-  #  echo "Making /gosa available in /etc/apache2/conf.d"
-
-  #  # Add GOsa include file
-  #  ln -s /etc/gosa/gosa-apache.conf /etc/apache2/conf-available/gosa.conf
-
-  #  if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
-  #    . /usr/share/apache2/apache2-maintscript-helper
-  #    apache2_invoke enconf gosa
-  #  fi
-  #fi
+if [ -d /etc/apache2 ]; then
+	if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
+		. /usr/share/apache2/apache2-maintscript-helper
+		apache2_invoke enconf $CONF
+	elif  dpkg-query -f '${Version}'  -W 'apache2.2-common' > /dev/null 2>&1 ; then
+		[ -d /etc/apache2/conf.d/ ] && [ ! -L /etc/apache2/conf.d/$CONF.conf ] && ln -s ../conf-available/$CONF.conf /etc/apache2/conf.d/$CONF.conf
+	fi
   
-  # Add support for RequestHeader
-  if ! apache2_invoke enmod headers ; then
-      echo "Failed to enable the apache2 headers module!"
-  fi
-
-  # Finally restart servers
-  #if [ -x /usr/sbin/invoke-rc.d ]; then
-  #  invoke-rc.d apache2 reload
-  #else
-  #  /etc/init.d/apache2 reload
-  #fi
+	# Add support for RequestHeader
+	if ! apache2_invoke enmod headers ; then
+		echo "Failed to enable the apache2 headers module!"
+	fi
 fi
 
 if [ -d /etc/lighttpd/conf-available ]; then
